/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SubcategoryDto } from '../models/subcategory-dto';
export interface CategoryDto {
  id: number;
  imagen_categoria?: string | null;
  nombre: string;
  subcategorias: Array<SubcategoryDto>;
}
