/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Login$Params as Login$Params } from './fn/autenticacion/login';
export { login as login } from './fn/autenticacion/login';
export type { GetCurrentUser$Params as GetCurrentUser$Params } from './fn/autenticacion/get-current-user';
export { getCurrentUser as getCurrentUser } from './fn/autenticacion/get-current-user';
export type { Register$Params as Register$Params } from './fn/autenticacion/register';
export { register as register } from './fn/autenticacion/register';
export type { Logout$Params as Logout$Params } from './fn/autenticacion/logout';
export { logout as logout } from './fn/autenticacion/logout';
export type { GetDashboardMetrics$Params as GetDashboardMetrics$Params } from './fn/dashboard/get-dashboard-metrics';
export { getDashboardMetrics as getDashboardMetrics } from './fn/dashboard/get-dashboard-metrics';
export type { GetOpenApiSpec$Params as GetOpenApiSpec$Params } from './fn/documentacion/get-open-api-spec';
export { getOpenApiSpec as getOpenApiSpec } from './fn/documentacion/get-open-api-spec';
