/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Login$Params as Login$Params } from './fn/autenticacion/login';
export { login as login } from './fn/autenticacion/login';
export type { GetCurrentUser$Params as GetCurrentUser$Params } from './fn/autenticacion/get-current-user';
export { getCurrentUser as getCurrentUser } from './fn/autenticacion/get-current-user';
export type { Register$Params as Register$Params } from './fn/autenticacion/register';
export { register as register } from './fn/autenticacion/register';
export type { Logout$Params as Logout$Params } from './fn/autenticacion/logout';
export { logout as logout } from './fn/autenticacion/logout';
export type { GetCategories$Params as GetCategories$Params } from './fn/categorias/get-categories';
export { getCategories as getCategories } from './fn/categorias/get-categories';
export type { GetDashboardMetrics$Params as GetDashboardMetrics$Params } from './fn/dashboard/get-dashboard-metrics';
export { getDashboardMetrics as getDashboardMetrics } from './fn/dashboard/get-dashboard-metrics';
export type { GetOpenApiSpec$Params as GetOpenApiSpec$Params } from './fn/documentacion/get-open-api-spec';
export { getOpenApiSpec as getOpenApiSpec } from './fn/documentacion/get-open-api-spec';
export type { GetProducts$Params as GetProducts$Params } from './fn/productos/get-products';
export { getProducts as getProducts } from './fn/productos/get-products';
export type { CreateProduct$Params as CreateProduct$Params } from './fn/productos/create-product';
export { createProduct as createProduct } from './fn/productos/create-product';
export type { GetProductById$Params as GetProductById$Params } from './fn/productos/get-product-by-id';
export { getProductById as getProductById } from './fn/productos/get-product-by-id';
export type { DeleteProduct$Params as DeleteProduct$Params } from './fn/productos/delete-product';
export { deleteProduct as deleteProduct } from './fn/productos/delete-product';
export type { GetProductImage$Params as GetProductImage$Params } from './fn/productos/get-product-image';
export { getProductImage as getProductImage } from './fn/productos/get-product-image';
export type { CheckFeaturedOrder$Params as CheckFeaturedOrder$Params } from './fn/productos/check-featured-order';
export { checkFeaturedOrder as checkFeaturedOrder } from './fn/productos/check-featured-order';
export type { ToggleProductStatus$Params as ToggleProductStatus$Params } from './fn/productos/toggle-product-status';
export { toggleProductStatus as toggleProductStatus } from './fn/productos/toggle-product-status';
