/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiResponse } from './models/api-response';
export type { CategoryDto } from './models/category-dto';
export type { ChartDto } from './models/chart-dto';
export type { CreateProductRequest } from './models/create-product-request';
export type { DashboardMetricsDto } from './models/dashboard-metrics-dto';
export type { InventoryMetricsDto } from './models/inventory-metrics-dto';
export type { LoginRequest } from './models/login-request';
export type { LoginResponse } from './models/login-response';
export type { ProductDto } from './models/product-dto';
export type { ProductResponse } from './models/product-response';
export type { RecentSaleDto } from './models/recent-sale-dto';
export type { RegisterRequest } from './models/register-request';
export type { SalesMetricsDto } from './models/sales-metrics-dto';
export type { SubcategoryDto } from './models/subcategory-dto';
export type { TopProductDto } from './models/top-product-dto';
export type { UserDto } from './models/user-dto';
